import {DEVICE_WINDOW_HEIGHT, DEVICE_WINDOW_WIDTH} from './device';

export const BOX_SIZE = 128;

export const BOX_START_X_POSITION = DEVICE_WINDOW_WIDTH / 2 - BOX_SIZE / 2;
export const BOX_START_Y_POSITION = DEVICE_WINDOW_HEIGHT / 2 - BOX_SIZE / 2;
