import {DEVICE_WINDOW_HEIGHT, DEVICE_WINDOW_WIDTH} from './device';

export const CARD_WIDTH = 215;
export const CARD_HEIGHT = 320;

export const CARD_ROTATION_DEG = 30;

export const CARD_START_X_POSITION = DEVICE_WINDOW_WIDTH / 2 - CARD_WIDTH / 2;
export const CARD_START_Y_POSITION = DEVICE_WINDOW_HEIGHT / 2 - CARD_WIDTH / 2;

export const CARD_ROTATION_OUTPUT = [-CARD_ROTATION_DEG, 0, CARD_ROTATION_DEG];
export const CARD_OPACITY_OUTPUT = [0.5, 1, 0.5];
export const CARD_SNAP_POINTS = [
  -DEVICE_WINDOW_WIDTH + CARD_WIDTH,
  0,
  DEVICE_WINDOW_WIDTH,
];
